apiversion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - host: 161.202.175.76
      http:
        paths:
          - path: /user
            pathType: prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80